const games = [
  // ─── ACTION / SHOOTER ───────────────────────────────────────────────
  {
    id: 1,
    title: "Elden Ring",
    platform: ["pc", "ps5", "xbox"],
    genre: ["action", "rpg"],
    vibe: ["adrenalin", "story", "solo"],
    multiplayer: false,
    releaseYear: 2022,
    rating: 9.5,
    difficulty: "hard",
    playTime: "60-100h",
    description: "Epische Open-World mit gnadenlosen Kämpfen und einer Welt die von George R.R. Martin miterschaffen wurde. Stirb, lerne, werde stärker.",
    tags: ["open-world", "souls-like", "fantasy", "dark"],
    image: "https://via.placeholder.com/300x200/1a1a2e/ffffff?text=Elden+Ring"
  },
  {
    id: 2,
    title: "God of War: Ragnarök",
    platform: ["pc", "ps5"],
    genre: ["action", "adventure"],
    vibe: ["adrenalin", "story", "solo"],
    multiplayer: false,
    releaseYear: 2022,
    rating: 9.4,
    difficulty: "medium",
    playTime: "25-40h",
    description: "Kratos und Atreus kämpfen sich durch die neun Welten der nordischen Mythologie. Brutal, emotional und wunderschön inszeniert.",
    tags: ["mythology", "story-rich", "cinematic", "action"],
    image: "https://via.placeholder.com/300x200/1a1a2e/ffffff?text=God+of+War"
  },
  {
    id: 3,
    title: "Hades",
    platform: ["pc", "ps5", "xbox", "switch"],
    genre: ["action", "roguelite"],
    vibe: ["adrenalin", "solo", "kurz"],
    multiplayer: false,
    releaseYear: 2020,
    rating: 9.3,
    difficulty: "medium",
    playTime: "20-90h",
    description: "Kämpfe dich aus der Unterwelt raus. Stirb, werde stärker, versuche es nochmal. Jeder Run fühlt sich anders an.",
    tags: ["roguelite", "mythology", "replayable", "fast-paced"],
    image: "https://via.placeholder.com/300x200/1a1a2e/ffffff?text=Hades"
  },
  {
    id: 4,
    title: "Doom Eternal",
    platform: ["pc", "ps5", "xbox", "switch"],
    genre: ["shooter", "action"],
    vibe: ["adrenalin", "solo", "kurz"],
    multiplayer: false,
    releaseYear: 2020,
    rating: 9.0,
    difficulty: "hard",
    playTime: "15-25h",
    description: "Non-stop Action auf maximaler Geschwindigkeit. Kein Spiel lässt dich so intensiv kämpfen wie Doom Eternal.",
    tags: ["fps", "fast-paced", "metal", "brutal"],
    image: "https://via.placeholder.com/300x200/1a1a2e/ffffff?text=Doom+Eternal"
  },
  {
    id: 5,
    title: "Sekiro: Shadows Die Twice",
    platform: ["pc", "ps5", "xbox"],
    genre: ["action", "adventure"],
    vibe: ["adrenalin", "story", "solo"],
    multiplayer: false,
    releaseYear: 2019,
    rating: 9.2,
    difficulty: "hard",
    playTime: "30-60h",
    description: "Japan im Sengoku-Zeitalter. Präzise Schwertkämpfe, die dich wirklich herausfordern. Das Erfolgsgefühl nach jedem Boss ist unbeschreiblich.",
    tags: ["samurai", "japan", "souls-like", "precise"],
    image: "https://via.placeholder.com/300x200/1a1a2e/ffffff?text=Sekiro"
  },
  {
    id: 6,
    title: "Devil May Cry 5",
    platform: ["pc", "ps5", "xbox"],
    genre: ["action"],
    vibe: ["adrenalin", "solo", "kurz"],
    multiplayer: false,
    releaseYear: 2019,
    rating: 8.8,
    difficulty: "medium",
    playTime: "12-20h",
    description: "Stylische Dämonenjagd mit drei spielbaren Charakteren. Je cooler du kämpfst, desto höher dein Score.",
    tags: ["stylish", "demons", "combo", "action"],
    image: "https://via.placeholder.com/300x200/1a1a2e/ffffff?text=DMC5"
  },
  {
    id: 7,
    title: "Ghostrunner",
    platform: ["pc", "ps5", "xbox", "switch"],
    genre: ["action", "platformer"],
    vibe: ["adrenalin", "solo", "kurz"],
    multiplayer: false,
    releaseYear: 2020,
    rating: 8.5,
    difficulty: "hard",
    playTime: "6-10h",
    description: "Ein Schwerthieb, ein Tod. Rase durch eine Cyberpunk-Stadt, stirb tausendmal und werde jedes Mal schneller.",
    tags: ["cyberpunk", "fast-paced", "one-hit", "parkour"],
    image: "https://via.placeholder.com/300x200/1a1a2e/ffffff?text=Ghostrunner"
  },
  {
    id: 8,
    title: "Control",
    platform: ["pc", "ps5", "xbox"],
    genre: ["action", "adventure"],
    vibe: ["story", "solo", "chill"],
    multiplayer: false,
    releaseYear: 2019,
    rating: 8.6,
    difficulty: "medium",
    playTime: "15-25h",
    description: "Ein mysteriöses Regierungsgebäude, übernatürliche Kräfte und eine Geschichte die dich nie loslässt. Unglaublich atmosphärisch.",
    tags: ["mystery", "supernatural", "atmosphere", "weird"],
    image: "https://via.placeholder.com/300x200/1a1a2e/ffffff?text=Control"
  },

  // ─── MULTIPLAYER / MIT FREUNDEN ─────────────────────────────────────
  {
    id: 9,
    title: "It Takes Two",
    platform: ["pc", "ps5", "xbox"],
    genre: ["adventure", "platformer"],
    vibe: ["freunde", "chill", "story"],
    multiplayer: true,
    releaseYear: 2021,
    rating: 9.4,
    difficulty: "easy",
    playTime: "12-15h",
    description: "Das beste Co-op-Spiel aller Zeiten. Ihr müsst zusammenarbeiten – perfekt für Freunde oder Partner. Jedes Kapitel spielt sich komplett anders.",
    tags: ["co-op", "couple", "creative", "story"],
    image: "https://via.placeholder.com/300x200/1a1a2e/ffffff?text=It+Takes+Two"
  },
  {
    id: 10,
    title: "Overcooked 2",
    platform: ["pc", "ps5", "xbox", "switch"],
    genre: ["simulation", "party"],
    vibe: ["freunde", "kurz", "chaos"],
    multiplayer: true,
    releaseYear: 2018,
    rating: 8.3,
    difficulty: "medium",
    playTime: "10-20h",
    description: "Koche mit Freunden und streite dabei aufs Blut. Lustig, chaotisch und garantiert für Drama.",
    tags: ["co-op", "cooking", "chaos", "party"],
    image: "https://via.placeholder.com/300x200/1a1a2e/ffffff?text=Overcooked+2"
  },
  {
    id: 11,
    title: "Fortnite",
    platform: ["pc", "ps5", "xbox", "switch"],
    genre: ["shooter", "battle-royale"],
    vibe: ["adrenalin", "freunde", "kurz"],
    multiplayer: true,
    releaseYear: 2017,
    rating: 8.0,
    difficulty: "medium",
    playTime: "endlos",
    description: "100 Spieler, einer gewinnt. Mit Freunden im Squad macht es nochmal 10x mehr Spaß. Immer neue Events und Skins.",
    tags: ["battle-royale", "free-to-play", "building", "competitive"],
    image: "https://via.placeholder.com/300x200/1a1a2e/ffffff?text=Fortnite"
  },
  {
    id: 12,
    title: "Rocket League",
    platform: ["pc", "ps5", "xbox", "switch"],
    genre: ["sport", "racing"],
    vibe: ["adrenalin", "freunde", "kurz"],
    multiplayer: true,
    releaseYear: 2015,
    rating: 8.7,
    difficulty: "medium",
    playTime: "endlos",
    description: "Fußball mit Autos. Klingt simpel, hat aber eine der steilsten Lernkurven überhaupt. Extrem befriedigend wenn es klappt.",
    tags: ["competitive", "skill-based", "free-to-play", "sport"],
    image: "https://via.placeholder.com/300x200/1a1a2e/ffffff?text=Rocket+League"
  },
  {
    id: 13,
    title: "Among Us",
    platform: ["pc", "switch"],
    genre: ["party", "strategy"],
    vibe: ["freunde", "kurz", "chaos"],
    multiplayer: true,
    releaseYear: 2018,
    rating: 8.0,
    difficulty: "easy",
    playTime: "endlos",
    description: "Finde den Verräter – oder sei selbst einer. Bringt jede Gruppe zum Lachen und zum Streiten.",
    tags: ["social-deduction", "party", "lying", "fun"],
    image: "https://via.placeholder.com/300x200/1a1a2e/ffffff?text=Among+Us"
  },
  {
    id: 14,
    title: "Fall Guys",
    platform: ["pc", "ps5", "xbox", "switch"],
    genre: ["party", "platformer"],
    vibe: ["freunde", "kurz", "chaos"],
    multiplayer: true,
    releaseYear: 2020,
    rating: 8.1,
    difficulty: "easy",
    playTime: "endlos",
    description: "60 Bohnen kämpfen in verrückten Minispielen um die Krone. Lustig, frustrierend und süchtig machend.",
    tags: ["battle-royale", "party", "casual", "funny"],
    image: "https://via.placeholder.com/300x200/1a1a2e/ffffff?text=Fall+Guys"
  },
  {
    id: 15,
    title: "Mario Kart 8 Deluxe",
    platform: ["switch"],
    genre: ["racing", "party"],
    vibe: ["freunde", "chill", "chaos"],
    multiplayer: true,
    releaseYear: 2017,
    rating: 9.2,
    difficulty: "easy",
    playTime: "endlos",
    description: "Der ultimative Couch-Multiplayer. Alle können mitspielen und alle werden sich wegen dem blauen Panzer streiten.",
    tags: ["racing", "party", "couch-co-op", "casual"],
    image: "https://via.placeholder.com/300x200/1a1a2e/ffffff?text=Mario+Kart+8"
  },
  {
    id: 16,
    title: "Minecraft",
    platform: ["pc", "ps5", "xbox", "switch"],
    genre: ["sandbox", "survival"],
    vibe: ["chill", "freunde", "kreativ"],
    multiplayer: true,
    releaseYear: 2011,
    rating: 9.5,
    difficulty: "easy",
    playTime: "endlos",
    description: "Baue alles was du dir vorstellen kannst. Alleine oder mit Freunden – kein Spiel hat mehr Freiheit.",
    tags: ["sandbox", "building", "survival", "creative"],
    image: "https://via.placeholder.com/300x200/1a1a2e/ffffff?text=Minecraft"
  },
  {
    id: 17,
    title: "Phasmophobia",
    platform: ["pc"],
    genre: ["horror", "simulation"],
    vibe: ["freunde", "chaos", "adrenalin"],
    multiplayer: true,
    releaseYear: 2020,
    rating: 8.5,
    difficulty: "medium",
    playTime: "endlos",
    description: "Geisterjäger-Simulator mit Freunden. Jeder redet mutig – bis das Licht ausgeht.",
    tags: ["horror", "co-op", "scary", "investigation"],
    image: "https://via.placeholder.com/300x200/1a1a2e/ffffff?text=Phasmophobia"
  },
  {
    id: 18,
    title: "Deep Rock Galactic",
    platform: ["pc", "xbox"],
    genre: ["shooter", "co-op"],
    vibe: ["freunde", "adrenalin", "kurz"],
    multiplayer: true,
    releaseYear: 2020,
    rating: 9.1,
    difficulty: "medium",
    playTime: "endlos",
    description: "Zwergische Weltraum-Bergmänner kämpfen gegen Alien-Horden. Teamwork ist alles. Rock and Stone!",
    tags: ["co-op", "aliens", "teamwork", "dwarves"],
    image: "https://via.placeholder.com/300x200/1a1a2e/ffffff?text=Deep+Rock"
  },

  // ─── STORY / SOLO ────────────────────────────────────────────────────
  {
    id: 19,
    title: "Red Dead Redemption 2",
    platform: ["pc", "ps5", "xbox"],
    genre: ["adventure", "action"],
    vibe: ["story", "chill", "solo"],
    multiplayer: false,
    releaseYear: 2018,
    rating: 9.7,
    difficulty: "easy",
    playTime: "60-100h",
    description: "Der Wilde Westen so lebendig wie nie. Reite, jage, lebe das Cowboy-Leben. Die beste Spielwelt die je erschaffen wurde.",
    tags: ["open-world", "western", "cinematic", "story-rich"],
    image: "https://via.placeholder.com/300x200/1a1a2e/ffffff?text=RDR2"
  },
  {
    id: 20,
    title: "The Witcher 3",
    platform: ["pc", "ps5", "xbox", "switch"],
    genre: ["rpg", "adventure"],
    vibe: ["story", "solo", "chill"],
    multiplayer: false,
    releaseYear: 2015,
    rating: 9.8,
    difficulty: "medium",
    playTime: "80-150h",
    description: "Geralt von Riva sucht seine Ziehtochter. Hunderte Stunden Content, tolle Charaktere und Entscheidungen die wirklich zählen.",
    tags: ["rpg", "fantasy", "open-world", "choices-matter"],
    image: "https://via.placeholder.com/300x200/1a1a2e/ffffff?text=Witcher+3"
  },
  {
    id: 21,
    title: "Cyberpunk 2077",
    platform: ["pc", "ps5", "xbox"],
    genre: ["rpg", "action"],
    vibe: ["story", "adrenalin", "solo"],
    multiplayer: false,
    releaseYear: 2020,
    rating: 9.0,
    difficulty: "medium",
    playTime: "50-100h",
    description: "Night City ist lebendig und gnadenlos. Seit dem Phantom Liberty DLC eine der besten Story-Erfahrungen überhaupt.",
    tags: ["cyberpunk", "rpg", "open-world", "futuristic"],
    image: "https://via.placeholder.com/300x200/1a1a2e/ffffff?text=Cyberpunk+2077"
  },
  {
    id: 22,
    title: "The Last of Us Part I",
    platform: ["pc", "ps5"],
    genre: ["adventure", "action"],
    vibe: ["story", "solo", "adrenalin"],
    multiplayer: false,
    releaseYear: 2013,
    rating: 9.5,
    difficulty: "medium",
    playTime: "15-20h",
    description: "Joel und Ellie überleben in einer post-apokalyptischen Welt. Emotional, brutal und cineastisch wie kein anderes Spiel.",
    tags: ["post-apocalyptic", "emotional", "story-rich", "survival"],
    image: "https://via.placeholder.com/300x200/1a1a2e/ffffff?text=The+Last+of+Us"
  },
  {
    id: 23,
    title: "Disco Elysium",
    platform: ["pc", "ps5"],
    genre: ["rpg", "adventure"],
    vibe: ["story", "solo", "chill"],
    multiplayer: false,
    releaseYear: 2019,
    rating: 9.6,
    difficulty: "easy",
    playTime: "25-40h",
    description: "Ein betrunkener Detektiv löst einen Mordfall. Das schreibend beste Spiel aller Zeiten. Für Leute die Bücher lieben.",
    tags: ["detective", "narrative", "rpg", "political"],
    image: "https://via.placeholder.com/300x200/1a1a2e/ffffff?text=Disco+Elysium"
  },
  {
    id: 24,
    title: "Horizon Zero Dawn",
    platform: ["pc", "ps5"],
    genre: ["action", "rpg"],
    vibe: ["story", "adrenalin", "solo"],
    multiplayer: false,
    releaseYear: 2017,
    rating: 8.9,
    difficulty: "medium",
    playTime: "30-50h",
    description: "Roboter-Dinosaurier in einer post-apokalyptischen Welt. Aloy kämpft sich durch eine fesselnde Geschichte.",
    tags: ["open-world", "robots", "sci-fi", "action"],
    image: "https://via.placeholder.com/300x200/1a1a2e/ffffff?text=Horizon"
  },
  {
    id: 25,
    title: "Ghost of Tsushima",
    platform: ["pc", "ps5"],
    genre: ["action", "adventure"],
    vibe: ["story", "adrenalin", "chill"],
    multiplayer: false,
    releaseYear: 2020,
    rating: 9.1,
    difficulty: "medium",
    playTime: "30-50h",
    description: "Samurai kämpft gegen die Mongolen-Invasion auf der Insel Tsushima. Wunderschöne Grafik, tolles Kampfsystem.",
    tags: ["samurai", "japan", "open-world", "beautiful"],
    image: "https://via.placeholder.com/300x200/1a1a2e/ffffff?text=Ghost+of+Tsushima"
  },
  {
    id: 26,
    title: "Mass Effect Legendary Edition",
    platform: ["pc", "ps5", "xbox"],
    genre: ["rpg", "shooter"],
    vibe: ["story", "solo", "adrenalin"],
    multiplayer: false,
    releaseYear: 2021,
    rating: 9.2,
    difficulty: "medium",
    playTime: "80-120h",
    description: "Die komplette Mass Effect Trilogie. Deine Entscheidungen in Teil 1 beeinflussen Teil 3. Die epischste Sci-Fi Geschichte im Gaming.",
    tags: ["sci-fi", "rpg", "choices-matter", "trilogy"],
    image: "https://via.placeholder.com/300x200/1a1a2e/ffffff?text=Mass+Effect"
  },
  {
    id: 27,
    title: "Alan Wake 2",
    platform: ["pc", "ps5", "xbox"],
    genre: ["horror", "adventure"],
    vibe: ["story", "solo", "adrenalin"],
    multiplayer: false,
    releaseYear: 2023,
    rating: 9.0,
    difficulty: "medium",
    playTime: "20-30h",
    description: "Ein Schriftsteller steckt in seinem eigenen Horrorgeschichte. Meta, düster und filmisch wie kein anderes Spiel.",
    tags: ["horror", "meta", "atmospheric", "thriller"],
    image: "https://via.placeholder.com/300x200/1a1a2e/ffffff?text=Alan+Wake+2"
  },

  // ─── CHILL / ENTSPANNT ───────────────────────────────────────────────
  {
    id: 28,
    title: "Stardew Valley",
    platform: ["pc", "ps5", "xbox", "switch"],
    genre: ["simulation", "rpg"],
    vibe: ["chill", "solo", "kreativ"],
    multiplayer: true,
    releaseYear: 2016,
    rating: 9.5,
    difficulty: "easy",
    playTime: "50-200h",
    description: "Bau deinen Bauernhof auf, knüpfe Freundschaften und vergiss dabei komplett die Zeit. Das entspannendste Spiel überhaupt.",
    tags: ["farming", "relaxing", "cozy", "pixel-art"],
    image: "https://via.placeholder.com/300x200/1a1a2e/ffffff?text=Stardew+Valley"
  },
  {
    id: 29,
    title: "Animal Crossing: New Horizons",
    platform: ["switch"],
    genre: ["simulation"],
    vibe: ["chill", "kreativ", "solo"],
    multiplayer: true,
    releaseYear: 2020,
    rating: 9.0,
    difficulty: "easy",
    playTime: "endlos",
    description: "Bau deine eigene Insel auf, sammle Möbel und hänge mit süßen Tiercharakteren ab. Kein Stress, keine Eile.",
    tags: ["cozy", "island", "creative", "casual"],
    image: "https://via.placeholder.com/300x200/1a1a2e/ffffff?text=Animal+Crossing"
  },
  {
    id: 30,
    title: "Journey",
    platform: ["pc", "ps5"],
    genre: ["adventure", "indie"],
    vibe: ["chill", "solo", "story"],
    multiplayer: false,
    releaseYear: 2012,
    rating: 9.3,
    difficulty: "easy",
    playTime: "2-3h",
    description: "Ein stilles Abenteuer durch eine Wüste. Keine Worte, keine Erklärungen – trotzdem emotional wie kaum ein anderes Spiel.",
    tags: ["emotional", "short", "beautiful", "meditative"],
    image: "https://via.placeholder.com/300x200/1a1a2e/ffffff?text=Journey"
  },
  {
    id: 31,
    title: "Unpacking",
    platform: ["pc", "ps5", "xbox", "switch"],
    genre: ["puzzle", "simulation"],
    vibe: ["chill", "solo", "kurz"],
    multiplayer: false,
    releaseYear: 2021,
    rating: 8.9,
    difficulty: "easy",
    playTime: "3-5h",
    description: "Räume eine Wohnung ein und entdecke dabei die Geschichte einer Person. Entspannend, nachdenklich und überraschend emotional.",
    tags: ["cozy", "pixel-art", "narrative", "relaxing"],
    image: "https://via.placeholder.com/300x200/1a1a2e/ffffff?text=Unpacking"
  },
  {
    id: 32,
    title: "Spiritfarer",
    platform: ["pc", "ps5", "xbox", "switch"],
    genre: ["simulation", "adventure"],
    vibe: ["chill", "story", "solo"],
    multiplayer: false,
    releaseYear: 2020,
    rating: 8.8,
    difficulty: "easy",
    playTime: "20-30h",
    description: "Begleite Seelen auf ihrem letzten Weg. Ein Spiel über den Tod das dich nicht traurig macht – sondern warm.",
    tags: ["emotional", "cozy", "death", "beautiful"],
    image: "https://via.placeholder.com/300x200/1a1a2e/ffffff?text=Spiritfarer"
  },
  {
    id: 33,
    title: "Abzû",
    platform: ["pc", "ps5", "xbox", "switch"],
    genre: ["adventure", "indie"],
    vibe: ["chill", "solo", "kurz"],
    multiplayer: false,
    releaseYear: 2016,
    rating: 8.5,
    difficulty: "easy",
    playTime: "2h",
    description: "Tauche in einen wunderschönen Ozean ein. Keine Gegner, keine Aufgaben – nur Schönheit und Entspannung.",
    tags: ["ocean", "meditative", "beautiful", "short"],
    image: "https://via.placeholder.com/300x200/1a1a2e/ffffff?text=Abzû"
  },

  // ─── STRATEGIE / KNOBELN ─────────────────────────────────────────────
  {
    id: 34,
    title: "Civilization VI",
    platform: ["pc", "ps5", "xbox", "switch"],
    genre: ["strategy"],
    vibe: ["brain", "solo", "chill"],
    multiplayer: true,
    releaseYear: 2016,
    rating: 9.0,
    difficulty: "hard",
    playTime: "endlos",
    description: "Baue eine Zivilisation von der Steinzeit bis ins Weltraumzeitalter. 'Nur noch eine Runde' – du weißt wie das endet.",
    tags: ["turn-based", "strategy", "history", "addictive"],
    image: "https://via.placeholder.com/300x200/1a1a2e/ffffff?text=Civ+VI"
  },
  {
    id: 35,
    title: "Slay the Spire",
    platform: ["pc", "ps5", "xbox", "switch"],
    genre: ["strategy", "roguelite"],
    vibe: ["brain", "solo", "kurz"],
    multiplayer: false,
    releaseYear: 2019,
    rating: 9.2,
    difficulty: "medium",
    playTime: "50-200h",
    description: "Baue ein Kartendeck und kämpfe dich durch einen Turm. Süchtig machend, tiefgründig und endlos replayable.",
    tags: ["card-game", "roguelite", "strategy", "addictive"],
    image: "https://via.placeholder.com/300x200/1a1a2e/ffffff?text=Slay+the+Spire"
  },
  {
    id: 36,
    title: "Into the Breach",
    platform: ["pc", "switch"],
    genre: ["strategy"],
    vibe: ["brain", "solo", "kurz"],
    multiplayer: false,
    releaseYear: 2018,
    rating: 9.1,
    difficulty: "hard",
    playTime: "20-80h",
    description: "Rundenbasierte Strategie auf einem 8x8 Raster. Jeder Zug hat perfekte Informationen – es ist immer deine Schuld wenn du verlierst.",
    tags: ["turn-based", "mechs", "aliens", "puzzle"],
    image: "https://via.placeholder.com/300x200/1a1a2e/ffffff?text=Into+the+Breach"
  },
  {
    id: 37,
    title: "Portal 2",
    platform: ["pc", "ps5", "xbox"],
    genre: ["puzzle", "adventure"],
    vibe: ["brain", "freunde", "story"],
    multiplayer: true,
    releaseYear: 2011,
    rating: 9.8,
    difficulty: "medium",
    playTime: "10-15h",
    description: "Löse physikbasierte Rätsel mit Portalen. Der Co-op Modus ist einer der besten je gemacht. GLaDOS ist unvergesslich.",
    tags: ["puzzle", "co-op", "funny", "physics"],
    image: "https://via.placeholder.com/300x200/1a1a2e/ffffff?text=Portal+2"
  },
  {
    id: 38,
    title: "Factorio",
    platform: ["pc"],
    genre: ["strategy", "simulation"],
    vibe: ["brain", "solo", "kreativ"],
    multiplayer: true,
    releaseYear: 2020,
    rating: 9.8,
    difficulty: "hard",
    playTime: "100-500h",
    description: "Baue eine Fabrik die sich selbst baut. Das tiefste und süchtigmachendste Spiel überhaupt. Warnung: Zeitfresser.",
    tags: ["factory", "automation", "complex", "addictive"],
    image: "https://via.placeholder.com/300x200/1a1a2e/ffffff?text=Factorio"
  },
  {
    id: 39,
    title: "Baldur's Gate 3",
    platform: ["pc", "ps5"],
    genre: ["rpg", "strategy"],
    vibe: ["brain", "story", "freunde"],
    multiplayer: true,
    releaseYear: 2023,
    rating: 9.8,
    difficulty: "medium",
    playTime: "100-200h",
    description: "Das beste RPG das je gemacht wurde. Jede Entscheidung zählt, jeder Charakter ist komplex und die Story endlos tief.",
    tags: ["d&d", "turn-based", "choices-matter", "epic"],
    image: "https://via.placeholder.com/300x200/1a1a2e/ffffff?text=Baldur%27s+Gate+3"
  },

  // ─── INDIE / KREATIV ─────────────────────────────────────────────────
  {
    id: 40,
    title: "Hollow Knight",
    platform: ["pc", "ps5", "xbox", "switch"],
    genre: ["action", "adventure"],
    vibe: ["adrenalin", "story", "brain"],
    multiplayer: false,
    releaseYear: 2017,
    rating: 9.4,
    difficulty: "hard",
    playTime: "40-60h",
    description: "Erkunde eine riesige unterirdische Welt voller Geheimnisse und Insekten. Schwer aber unglaublich befriedigend.",
    tags: ["metroidvania", "insects", "atmospheric", "precise"],
    image: "https://via.placeholder.com/300x200/1a1a2e/ffffff?text=Hollow+Knight"
  },
  {
    id: 41,
    title: "Celeste",
    platform: ["pc", "ps5", "xbox", "switch"],
    genre: ["platformer"],
    vibe: ["adrenalin", "story", "brain"],
    multiplayer: false,
    releaseYear: 2018,
    rating: 9.5,
    difficulty: "hard",
    playTime: "8-15h",
    description: "Besteige einen Berg – innerlich und äußerlich. Ein Plattformer über mentale Gesundheit der trotzdem herausfordernd ist.",
    tags: ["platformer", "mental-health", "precise", "emotional"],
    image: "https://via.placeholder.com/300x200/1a1a2e/ffffff?text=Celeste"
  },
  {
    id: 42,
    title: "Undertale",
    platform: ["pc", "ps5", "xbox", "switch"],
    genre: ["rpg", "indie"],
    vibe: ["story", "chill", "solo"],
    multiplayer: false,
    releaseYear: 2015,
    rating: 9.5,
    difficulty: "easy",
    playTime: "6-15h",
    description: "Ein RPG wo du niemanden töten musst. Voller Humor, Herz und Überraschungen die du nicht kommen siehst.",
    tags: ["meta", "funny", "emotional", "unique"],
    image: "https://via.placeholder.com/300x200/1a1a2e/ffffff?text=Undertale"
  },
  {
    id: 43,
    title: "Ori and the Will of the Wisps",
    platform: ["pc", "xbox", "switch"],
    genre: ["platformer", "adventure"],
    vibe: ["chill", "story", "adrenalin"],
    multiplayer: false,
    releaseYear: 2020,
    rating: 9.3,
    difficulty: "medium",
    playTime: "10-15h",
    description: "Das schönste Plattformer das je gemacht wurde. Bewegende Geschichte, wunderschöne Grafik und präzises Gameplay.",
    tags: ["beautiful", "emotional", "platformer", "metroidvania"],
    image: "https://via.placeholder.com/300x200/1a1a2e/ffffff?text=Ori"
  },
  {
    id: 44,
    title: "Cuphead",
    platform: ["pc", "ps5", "xbox", "switch"],
    genre: ["action", "platformer"],
    vibe: ["adrenalin", "freunde", "kurz"],
    multiplayer: true,
    releaseYear: 2017,
    rating: 9.0,
    difficulty: "hard",
    playTime: "10-20h",
    description: "1930er Cartoon-Stil trifft auf gnadenlose Boss-Kämpfe. Schön anzusehen, brutal zum spielen. Zu zweit machbar.",
    tags: ["boss-rush", "cartoon", "hard", "beautiful"],
    image: "https://via.placeholder.com/300x200/1a1a2e/ffffff?text=Cuphead"
  },

  // ─── OPEN WORLD / ERKUNDEN ────────────────────────────────────────────
  {
    id: 45,
    title: "The Legend of Zelda: Breath of the Wild",
    platform: ["switch"],
    genre: ["adventure", "action"],
    vibe: ["chill", "story", "brain"],
    multiplayer: false,
    releaseYear: 2017,
    rating: 9.7,
    difficulty: "medium",
    playTime: "50-100h",
    description: "Erkunde Hyrule in alle Richtungen. Keine Regeln, kein vorgeschriebener Weg – einfach Freiheit.",
    tags: ["open-world", "freedom", "exploration", "zelda"],
    image: "https://via.placeholder.com/300x200/1a1a2e/ffffff?text=Zelda+BOTW"
  },
  {
    id: 46,
    title: "The Legend of Zelda: Tears of the Kingdom",
    platform: ["switch"],
    genre: ["adventure", "action"],
    vibe: ["chill", "story", "brain", "kreativ"],
    multiplayer: false,
    releaseYear: 2023,
    rating: 9.8,
    difficulty: "medium",
    playTime: "60-120h",
    description: "Bau Maschinen, erkunde den Himmel und die Tiefe Hyrules. Noch mehr Freiheit als BotW – kreativ grenzenlos.",
    tags: ["open-world", "creative", "building", "zelda"],
    image: "https://via.placeholder.com/300x200/1a1a2e/ffffff?text=Zelda+TOTK"
  },
  {
    id: 47,
    title: "GTA V",
    platform: ["pc", "ps5", "xbox"],
    genre: ["action", "adventure"],
    vibe: ["adrenalin", "freunde", "chaos"],
    multiplayer: true,
    releaseYear: 2013,
    rating: 9.0,
    difficulty: "easy",
    playTime: "30-endlos",
    description: "Los Santos lebt. Ob Story oder Online mit Freunden – immer gibt es etwas Neues zu entdecken oder anzustellen.",
    tags: ["open-world", "crime", "online", "freedom"],
    image: "https://via.placeholder.com/300x200/1a1a2e/ffffff?text=GTA+V"
  },
  {
    id: 48,
    title: "No Man's Sky",
    platform: ["pc", "ps5", "xbox", "switch"],
    genre: ["adventure", "simulation"],
    vibe: ["chill", "kreativ", "solo"],
    multiplayer: true,
    releaseYear: 2016,
    rating: 8.7,
    difficulty: "easy",
    playTime: "endlos",
    description: "Unendlich viele Planeten zum Erkunden. Baue Basen, handle mit Aliens und verliere dich im Weltraum.",
    tags: ["space", "exploration", "building", "infinite"],
    image: "https://via.placeholder.com/300x200/1a1a2e/ffffff?text=No+Man%27s+Sky"
  },
  {
    id: 49,
    title: "Subnautica",
    platform: ["pc", "ps5", "xbox"],
    genre: ["adventure", "survival"],
    vibe: ["story", "chill", "solo"],
    multiplayer: false,
    releaseYear: 2018,
    rating: 9.3,
    difficulty: "medium",
    playTime: "30-50h",
    description: "Überlebe auf einem Ozeanplaneten. Tauche tiefer und entdecke was im Dunkeln wartet. Spannend und gruselig zugleich.",
    tags: ["ocean", "survival", "exploration", "atmospheric"],
    image: "https://via.placeholder.com/300x200/1a1a2e/ffffff?text=Subnautica"
  },
  {
    id: 50,
    title: "Outer Wilds",
    platform: ["pc", "ps5", "xbox"],
    genre: ["adventure", "indie"],
    vibe: ["story", "brain", "chill"],
    multiplayer: false,
    releaseYear: 2019,
    rating: 9.6,
    difficulty: "medium",
    playTime: "15-25h",
    description: "Erkunde ein Sonnensystem das alle 22 Minuten endet. Das Spiel mit dem besten Ende das je geschrieben wurde.",
    tags: ["mystery", "space", "exploration", "unique"],
    image: "https://via.placeholder.com/300x200/1a1a2e/ffffff?text=Outer+Wilds"
  }
];

const vibes = [
  { id: "adrenalin", label: "Adrenalin", desc: "Action, schnell, intensiv", icon: "🔥" },
  { id: "chill",     label: "Chill",     desc: "Entspannt, kein Stress",   icon: "😴" },
  { id: "freunde",   label: "Mit Freunden", desc: "Multiplayer, Co-op",    icon: "👥" },
  { id: "story",     label: "Story",     desc: "Epische Handlung",         icon: "📖" },
  { id: "brain",     label: "Knobeln",   desc: "Strategie, Denken",        icon: "🧠" },
  { id: "kreativ",   label: "Kreativ",   desc: "Bauen, Gestalten",         icon: "🎨" },
  { id: "kurz",      label: "Kurze Session", desc: "1-2 Stunden reichen", icon: "⚡" },
  { id: "chaos",     label: "Chaos",     desc: "Lustig, unberechenbar",    icon: "💥" }
];

const platforms = [
  { id: "pc",    label: "PC / Steam" },
  { id: "ps5",   label: "PS5" },
  { id: "xbox",  label: "Xbox" },
  { id: "switch",label: "Switch" }
];

const genres = [
  "action", "adventure", "rpg", "shooter", "strategy",
  "simulation", "puzzle", "platformer", "horror", "sport",
  "racing", "indie", "sandbox", "roguelite", "party"
];

function filterGames({ vibes: selectedVibes = [], platforms: selectedPlatforms = [], genres: selectedGenres = [], multiplayerOnly = false, search = "" }) {
  return games.filter(game => {
    if (selectedVibes.length > 0 && !selectedVibes.some(v => game.vibe.includes(v))) return false;
    if (selectedPlatforms.length > 0 && !selectedPlatforms.some(p => game.platform.includes(p))) return false;
    if (selectedGenres.length > 0 && !selectedGenres.some(g => game.genre.includes(g))) return false;
    if (multiplayerOnly && !game.multiplayer) return false;
    if (search && !game.title.toLowerCase().includes(search.toLowerCase())) return false;
    return true;
  });
}

function getRandomGame(filters = {}) {
  const filtered = filterGames(filters);
  if (filtered.length === 0) return null;
  return filtered[Math.floor(Math.random() * filtered.length)];
}

function getGameById(id) {
  return games.find(g => g.id === id) || null;
}